const etu = require('./chris.yao/EncodeTinyURL/solution');
const ts = require('./chris.yao/Two_Sum/solution');
const ss = require('./chris.yao/Subsets/solution');
const pp = require('./chris.yao/Palindrome_Permutation/solution');
const ocm = require('./chris.yao/Output_Contest_Matches/solution');
const gss = require('./chris.yao/Group_Shifted_Strings/solution');
const vs = require('./chris.yao/Valid_Soduku/solution');
const aasw = require('./chris.yao/Add_And_Search_Word/solution');
const qrbh = require('./chris.yao/Queue_Reconstruction_by_Height/solution');
const llwk = require('./chris.yao/Longest_Substring_with_At_Most_K_Distinct_Characters/solution');
const tsum = require('./chris.yao/3Sum/solution');
const sdn = require('./chris.yao/Selft_Dividing_Number/solution');
const hd = require('./chris.yao/Hamming_Distance/solution');
const vp = require('./chris.yao/Valid_Palindrome/solution');
const iota = require('./chris.yao/Intersection_of_Two_Arrays_II/solution');
const vp2 = require('./chris.yao/Valid_Palindrome_II/solution');
const dsg = require('./chris.yao/Design_Snake_Game/solution');
const motsa = require('./chris.yao/Median_of_Two_Sorted_Arrays/solution');
const cwmw = require('./chris.yao/Container_With_Most_Water/solution');
const rss = require('./chris.yao/Reverse_String_II/solution');
const cas = require('./chris.yao/Count_and_Say/solution');
const trw = require('./chris.yao/Trapping_Rain_Water/solution');
const lswr = require('./chris.yao/Longest_Substring_Without_Repeating_Characters/solution');
const ppig = require('./chris.yao/Poor_Pigs/solution');
const sp = require('./chris.yao/Shortest_Palindrome/solution');
const pap = require('./chris.yao/Palindrome_Pairs/solution');
const ma = require('./chris.yao/Accounts_Merge/solution');
const iv = require('./chris.yao/Valid_Parentheses/solution');
const lcp = require('./chris.yao/Longest_Common_Prefix/solution');
const main = () => {
    //etu.run();
    //ts.run();
    //ss.run();
    //pp.run();
    //ocm.run();
    //gss.run();
    // vs.run();
    // aasw.run();
    //qrbh.run();
    //llwk.run();
    //tsum.run();
    // sdn.run();
    //hd.run();
    // vp.run();
    // iota.run();
    // vp2.run();
    // dsg.run();
    //motsa.run();
    // cwmw.run();
    //rss.run();
    // cas.run();
    //trw.run();
    //lswr.run();
    //ppig.run();
     //sp.run();
    // pap.run();
    // ma.run();
    // iv.run();
    lcp.run();

};


module.exports.main = main;